name: 'Yarn Install'
description: 'Install Dependencies with Yarn'
inputs:
  npm_version:  # id of input
    description: 'Who to greet'
    required: true
    default: '14'
runs:
  using: "composite"
  steps:
    - name: Use Node.js ${{ inputs.npm_version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.npm_version }}
        cache: 'yarn'
    
    - name: Yarn Install
      run: yarn install
      shell: bash