name: 'Yarn Install'
description: 'Install Dependencies with Yarn'
inputs:
  node_version:
    description: 'Node version'
    required: true
    default: '14'
runs:
  using: "composite"
  steps:
    - name: Use Node.js ${{ inputs.node_version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node_version }}
        cache: 'yarn'
    
    - name: Yarn Install
      run: yarn install
      shell: bash