name: 'Yarn Install'
description: 'Install Dependencies with Yarn'
inputs:
  node_version:
    description: 'Node version'
    required: true
    default: '14'
  snyk_token:
    description: 'Snyk Token'
    required: true
runs:
  using: "composite"
  steps:
    - name: Install Node Dependencies
      uses: nolram/github-actions/actions/yarn_install@main
      with:
        node_version: ${{ inputs.node_version }}

    - name: Snyk monitor
      uses: snyk/actions/node@master
      env:
        SNYK_TOKEN: ${{ inputs.SNYK_TOKEN }}
