name: 'Yarn Install'
description: 'Install Dependencies with Yarn'
inputs:
  snyk_token:
    description: 'Snyk Token'
    required: true
  python_version:
    description: 'Python version'
    required: true
    default: '3.8'
runs:
  using: "composite"
  steps:
    - name: Install Python Dependencies
      uses: nolram/github-actions/actions/python_install@main
      with:
        python_version: ${{ inputs.python_version }}

    - name: Snyk monitor
      uses: snyk/actions/python@master
      continue-on-error: true # To make sure that SARIF upload gets called
      env:
        SNYK_TOKEN: ${{ inputs.snyk_token }}
      with:
        args: --sarif-file-output=snyk.sarif

    - name: Upload result to GitHub Code Scanning
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: snyk.sarif
