name: 'Yarn Install'
description: 'Install Dependencies with Yarn'
inputs:
  snyk_token:
    description: 'Snyk Token'
    required: true
  python_version:
    description: 'Python version'
    required: true
    default: '3.8'
runs:
  using: "composite"
  steps:
    - name: Install Python Dependencies
      uses: nolram/github-actions/actions/python_install@main
      with:
        python_version: ${{ inputs.python_version }}

    - name: Snyk monitor
      uses: snyk/actions/python@master
      env:
        SNYK_TOKEN: ${{ inputs.SNYK_TOKEN }}
