name: 'Yarn Install'
description: 'Install Dependencies with Yarn'
inputs:
  project_type:
    description: 'Project type'
    required: true
    default: 'node'
  snyk_token:
    description: 'Snyk Token'
    required: true
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@master
    - name: Run Snyk to check for vulnerabilities
      uses: snyk/actions/${{ inputs.project_type }}@master
      env:
        SNYK_TOKEN: ${{ inputs.snyk_token }}