name: Run Snyk and other tools to check vulnerabilities

on:
  workflow_call:
    inputs:
      project_type:
        required: true
        type: string
        default: "node"
    secrets:
      SNYK_TOKEN:
        required: true

permissions:
  id-token: write
  contents: read
  security-events: write

jobs:
  snyk_run:
    runs-on: ubuntu-latest
    environment: production
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - id: check_vulnerability_python
      if: ${{ inputs.project_type == 'python' }}
      uses: nolram/github-actions/actions/check_vulnerability_python@main
      with:
        snyk_token: ${{ secrets.SNYK_TOKEN }}
    
    - id: check_vulnerability_node
      if: ${{ inputs.project_type == 'node' }}
      uses: nolram/github-actions/actions/check_vulnerability_node@main
      with:
        snyk_token: ${{ secrets.SNYK_TOKEN }}
