name: Build Docker Image, push to ECR and Deploy to Kubernetes

on:
  workflow_call:
    inputs:
      AWS_REGION:
        required: true
        type: string
      project_type:
        required: true
        type: string
        default: "python"
    secrets:
      AWS_ROLE_ECR:
        required: true
      SNYK_TOKEN:
        required: true

jobs:
  quality_code:
    runs-on: ubuntu-latest
    environment: production
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - id: check_vulnerability_node
      if: ${{ inputs.project_type == "node" }}
      uses: nolram/github-actions/actions/check_vulnerability_node@main
      with:
        snyk_token: ${{ secrets.SNYK_TOKEN }}

    - id: check_vulnerability_python
      if: ${{ inputs.project_type == "python" }}
      uses: nolram/github-actions/actions/check_vulnerability_python@main
      with:
        snyk_token: ${{ secrets.SNYK_TOKEN }}

  deploy:
    runs-on: ubuntu-latest
    environment: production
    needs: quality_code
    
    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - id: node_dependencies
      if: ${{ inputs.project_type == "node" }}
      uses: nolram/github-actions/actions/yarn_install@main

    - id: python_dependencies
      if: ${{ inputs.project_type == "python" }}
      uses: nolram/github-actions/actions/python_install@main

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-region: ${{ inputs.AWS_REGION }}
        role-to-assume: ${{ secrets.AWS_ROLE_ECR }}

